03 objects and arrays
js-tasks-ru/js-20210427_anton8 pull request #3
Opened 2021-05-05 08:48 UTC by tropikan42

2021-05-05 08:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-06 11:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathArr = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-05-06 11:20 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
good 👍

2021-05-06 11:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let currentSymbol = string[0];
можно использовать деструктурирующее присваивание:
```
let [currentSymbol] = string;
```
тогда в переменную `currentSymbol` попадет первый элемент `string`

2021-05-06 11:21 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
>  export function uniq(arr) {
good 👍

2021-05-06 11:22 UTC, dosandk requested changes
хорошо, но нужно поправить решение `createGetter`

2021-05-10 19:18 UTC, dosandk approved these changes

2021-05-10 19:19 UTC, merged